### PR TITLE
Update to python 3 compatibility.

### PR DESCRIPTION
**Pull request by ataber**
Thanks for the great library! 

In order to get ready for Python 2 phase-out, I ran `2to3` on the codebase and made some other manual changes.

### CODE REVIEW

**Comment by vkhodygo** [comment]
We still have that issue with sparse matrices support in py3. 
I've been looking for some free time to fix this issue for ages.

**Comment by williamhunter** [comment]
> 
> 
> We still have that issue with sparse matrices support in py3.
> I've been looking for some free time to fix this issue for ages.

Hi Vladimir,

Yes, I remember at the time that Pysparse gave the best performance of all the libs I tested at the time. The lib that comes standard with SciPy was horribly slow (orders). Of course a lot could've changed since then!

I suspect that CHOLMOD (via https://pypi.org/project/scikit-sparse/) will give similar or hopefully better performance than Pysparse, but I've not had the time or inclination to implement it. It should be easier to install than Pysparse, and that is the main thing.

Regards,
William

**Comment by williamhunter** [comment]
> 
> 
> Thanks for the great library!
> 
> In order to get ready for Python 2 phase-out, I ran `2to3` on the codebase and made some other manual changes.

Thanks Andrew, I merged.

**Comment by ataber** [comment]
Thanks for the merge. I should point out for posterity that this code does not quite work with python3, because `pysparse` still needs to be updated/replaced. However it hasn't broken python2 compatibility AFAIK.

**Pull request merged**
