### PR TITLE
Apply pep8 codestyle

### PR DESCRIPTION
**Pull request by caiocarrara**
This is much more a purpose and an example of what must be done in project codestyle. This pull request apply a bunch of pep8[1] recomendations. It's important to follow this convention so the project would be more readable to new contributors.

Trying to apply pep8 some code improvements can be noted. For example: there's some operations too long that would be better if splitted in more than one instruction as the snippet below:
```python
# bad style
operation = a + b + c * (c + f + j) / (a + b + c) ** 2

# better style
initial_operation = a + b + c
second_operation = initial_operation * (c + f + j)
other_meaning_name_operation = (a + b + c) ** 2
conclution_operation = second_operation / other_meaning_name_operation
```

Other thing. What about migrating the code to Python 3? 👍

### CODE REVIEW

**Comment by caiocarrara** [comment]
What do you think about it? Should I continue or stop with this changes? I think it would be a great improvement make codebase better formatted.

**Comment by ISosnovik** [comment]
You are right. The repo needs refactoring and cleaning. However, you PR has conflicts. It would be great if refactor/clean the current version of ToPy.

**Comment by caiocarrara** [comment]
No more conflicts. However, since the project has no tests, I would recommend you run your usual tests there from my branch so we can have a least some safety I didn't break anything.

**Comment by williamhunter** [comment]
Apologies for the delay in merging, I don't come here that often anymore.

**Comment by ISosnovik** [comment]
This commit is not worth merging.
`topy` does not work

**Comment by vkhodygo** [comment]
@williamhunter  You need to give PR access to someone since you can't (or don't want to) do this any more.

**Comment by williamhunter** [comment]
I've added @V-Kh and @cacarrara as collaborators. I think @ISosnovik is probably best suited to steer the direction of ToPy -- while still close to my hart I've moved on to other things.

**Pull request merged**
